-- Migration: Add forecast storage tables
-- Created: 2025-10-10
-- Description: Add tables for storing day forecasts, swing forecasts, and advanced forecasts

\c ai_market_system;

-- Create forecast_type enum
DO $$ BEGIN
    CREATE TYPE forecast_type AS ENUM ('day', 'swing', 'advanced');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create signal_type enum
DO $$ BEGIN
    CREATE TYPE signal_type AS ENUM ('BUY', 'SELL', 'HOLD');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create day_forecasts table
CREATE TABLE IF NOT EXISTS day_forecasts (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    direction signal_type NOT NULL,
    confidence DECIMAL(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    target_price DECIMAL(10,2),
    stop_loss DECIMAL(10,2),
    current_price DECIMAL(10,2),
    predicted_price DECIMAL(10,2),
    price_change DECIMAL(8,4),
    volume_forecast VARCHAR(20),
    risk_score DECIMAL(5,4),
    signal_strength VARCHAR(20),
    technical_indicators JSONB,
    market_regime VARCHAR(50),
    volatility_forecast VARCHAR(20),
    key_events JSONB,
    macro_factors JSONB,
    fundamental_score DECIMAL(5,4),
    sentiment_score DECIMAL(5,4),
    horizon VARCHAR(20) DEFAULT 'end_of_day',
    valid_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_day_forecasts_symbol 
        FOREIGN KEY (symbol) REFERENCES symbols (symbol) ON DELETE CASCADE
);

-- Create swing_forecasts table
CREATE TABLE IF NOT EXISTS swing_forecasts (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    direction signal_type NOT NULL,
    confidence DECIMAL(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    target_price DECIMAL(10,2),
    stop_loss DECIMAL(10,2),
    current_price DECIMAL(10,2),
    predicted_price DECIMAL(10,2),
    price_change DECIMAL(8,4),
    trend VARCHAR(20),
    support_level DECIMAL(10,2),
    resistance_level DECIMAL(10,2),
    risk_score DECIMAL(5,4),
    signal_strength VARCHAR(20),
    technical_indicators JSONB,
    market_regime VARCHAR(50),
    volume_forecast VARCHAR(20),
    volatility_forecast VARCHAR(20),
    key_events JSONB,
    macro_factors JSONB,
    fundamental_score DECIMAL(5,4),
    sentiment_score DECIMAL(5,4),
    horizon VARCHAR(20) DEFAULT 'medium_swing',
    valid_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_swing_forecasts_symbol 
        FOREIGN KEY (symbol) REFERENCES symbols (symbol) ON DELETE CASCADE
);

-- Create advanced_forecasts table
CREATE TABLE IF NOT EXISTS advanced_forecasts (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    final_signal signal_type NOT NULL,
    final_confidence DECIMAL(5,4) NOT NULL CHECK (final_confidence BETWEEN 0 AND 1),
    current_price DECIMAL(10,2),
    predicted_price DECIMAL(10,2),
    target_price DECIMAL(10,2),
    stop_loss DECIMAL(10,2),
    price_change_pct DECIMAL(8,4),
    risk_score DECIMAL(5,4),
    signal_strength VARCHAR(20),
    agent_contributions JSONB,
    total_agents_contributing INTEGER DEFAULT 0,
    signal_distribution JSONB,
    ensemble_signal JSONB,
    rag_analysis JSONB,
    rl_recommendation JSONB,
    meta_evaluation JSONB,
    latent_patterns JSONB,
    forecast_type VARCHAR(50) DEFAULT 'Advanced Multi-Agent Forecast',
    valid_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_advanced_forecasts_symbol 
        FOREIGN KEY (symbol) REFERENCES symbols (symbol) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_day_forecasts_symbol ON day_forecasts(symbol);
CREATE INDEX IF NOT EXISTS idx_day_forecasts_created_at ON day_forecasts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_day_forecasts_direction ON day_forecasts(direction);

CREATE INDEX IF NOT EXISTS idx_swing_forecasts_symbol ON swing_forecasts(symbol);
CREATE INDEX IF NOT EXISTS idx_swing_forecasts_created_at ON swing_forecasts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_swing_forecasts_direction ON swing_forecasts(direction);

CREATE INDEX IF NOT EXISTS idx_advanced_forecasts_symbol ON advanced_forecasts(symbol);
CREATE INDEX IF NOT EXISTS idx_advanced_forecasts_created_at ON advanced_forecasts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_advanced_forecasts_final_signal ON advanced_forecasts(final_signal);

-- Add comments for documentation
COMMENT ON TABLE day_forecasts IS 'Stores day trading forecasts generated by the forecasting system';
COMMENT ON TABLE swing_forecasts IS 'Stores swing trading forecasts for 3-10 day horizons';
COMMENT ON TABLE advanced_forecasts IS 'Stores advanced multi-agent forecasts using all 15 AI agents';

COMMENT ON COLUMN day_forecasts.horizon IS 'Forecast horizon: end_of_day, next_day';
COMMENT ON COLUMN swing_forecasts.horizon IS 'Forecast horizon: short_swing, medium_swing, long_swing';
COMMENT ON COLUMN advanced_forecasts.agent_contributions IS 'Array of individual agent predictions';
COMMENT ON COLUMN advanced_forecasts.ensemble_signal IS 'Blended signal from ensemble system';
COMMENT ON COLUMN advanced_forecasts.rag_analysis IS 'RAG Event Agent analysis data';
COMMENT ON COLUMN advanced_forecasts.rl_recommendation IS 'RL Strategy Agent recommendation';
COMMENT ON COLUMN advanced_forecasts.meta_evaluation IS 'Meta-Evaluation Agent ranking';
COMMENT ON COLUMN advanced_forecasts.latent_patterns IS 'Latent Pattern Detector insights';

